[package]
name = "fed_tools"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "filter_feed"
path = "src/filter_feed.rs"

[[bin]]
name = "generate_schema"
path = "src/generate_schema.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
fed = { path = "../fed" }
eventually_api = { path = "../eventually_api" }
indicatif = "0.18.4"
json-structural-diff = "0.2.0"
schemars = { version = "1.2.1", features = ["chrono04", "uuid1", "preserve_order"] }
with_structure = { path = "../with_structure" }
serde_json = "1.0.149"
chrono = "0.4.44"
itertools = "0.14.0"
uuid = "1.23.1"
