[workspace]

members = [
    "enum_flatten",
    "enum_flatten_derive",
    "eventually_api",
    "fed",
    "fed_server",
    "fed_tools",
    "with_structure",
    "with_structure_derive",
]

resolver = "2"