[package]
name = "with_structure"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1.23.1"
chrono = "0.4.44"
perfect-derive = "0.1.5"
either = { version = "1.15.0", optional = true }
with_structure_derive = { path = "../with_structure_derive" }
serde = { version = "1.0.229", features = ["derive"], optional = true }